"use client";

import { useAuth } from "@/context/AuthContext";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from "recharts";

const COLORS = ['#FF6B35', '#2E4057', '#1D976C'];

interface InvoiceItem {
  id: number;
  category: string;
  description: string;
  qty: string;
  unitCost: number;
  amount: number;
}

interface TripData {
  title: string;
  duration: string;
  cities: string;
  invoiceId: string;
  generatedDate: string;
  travelers: string[];
  paymentStatus: string;
  totalBudget: number;
  totalSpent: number;
  expenses: InvoiceItem[];
}

export default function BillingPage() {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  
  const [tripData] = useState<TripData>({
    title: "Trip to Europe Adventure",
    duration: "May 25 - Jun 05, 2025",
    cities: "4 cities",
    invoiceId: "INV-xyz-30290",
    generatedDate: "May 20, 2025",
    travelers: ["James", "Arjun", "Jerry", "Cristina"],
    paymentStatus: "pending",
    totalBudget: 20000,
    totalSpent: 22000,
    expenses: [
      { id: 1, category: "Accommodation", description: "Hotel booking in Paris", qty: "4 nights", unitCost: 2500, amount: 10000 },
      { id: 2, category: "Transportation", description: "Flight bookings (DEL → PAR)", qty: "2 tickets", unitCost: 3500, amount: 7000 },
      { id: 3, category: "Food & Dining", description: "Restaurant reservations", qty: "8 meals", unitCost: 250, amount: 2000 },
      { id: 4, category: "Activities", description: "Tour packages", qty: "4 tours", unitCost: 750, amount: 3000 },
      { id: 5, category: "Miscellaneous", description: "Travel insurance", qty: "1", unitCost: 500, amount: 500 },
    ],
  });

  const [searchTerm, setSearchTerm] = useState("");
  const [paymentStatus, setPaymentStatus] = useState("pending");
  const [showMessage, setShowMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!authLoading && !user) {
      router.push("/login");
    }
  }, [user, authLoading, router]);

  const downloadInvoice = () => {
    const invoiceText = `
=====================================
TRAVELOOP INVOICE
=====================================

Invoice ID: ${tripData.invoiceId}
Generated Date: ${tripData.generatedDate}
Trip: ${tripData.title}
Duration: ${tripData.duration}
Cities: ${tripData.cities}

TRAVELERS:
${tripData.travelers.map(t => `- ${t}`).join('\n')}

=====================================
EXPENSE DETAILS
=====================================

${filteredExpenses.map((e, i) => `${i + 1}. ${e.category}: ${e.description}
   Qty: ${e.qty} | Unit Cost: $${e.unitCost} | Amount: $${e.amount}`).join('\n\n')}

=====================================
BILLING SUMMARY
=====================================

Subtotal: $${subtotal.toLocaleString()}
Tax (5%): $${tax.toLocaleString()}
Discount: -$${discount}
-------------------------------------
GRAND TOTAL: $${grandTotal.toLocaleString()}
=====================================

Payment Status: ${paymentStatus.toUpperCase()}

Generated by Traveloop
=====================================
    `.trim();

    const blob = new Blob([invoiceText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${tripData.invoiceId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    setShowMessage("Invoice downloaded successfully!");
    setTimeout(() => setShowMessage(null), 3000);
  };

  const exportPDF = () => {
    setShowMessage("PDF export feature coming soon! You can use the Download Invoice button for now.");
    setTimeout(() => setShowMessage(null), 4000);
  };

  const markAsPaid = () => {
    setPaymentStatus("paid");
    setShowMessage("Payment marked as paid!");
    setTimeout(() => setShowMessage(null), 3000);
  };

  const budgetRemaining = tripData.totalBudget - tripData.totalSpent;
  const budgetData = [
    { name: 'Spent', value: tripData.totalSpent },
    { name: 'Remaining', value: Math.abs(budgetRemaining) },
  ];

  const subtotal = tripData.expenses.reduce((sum, item) => sum + item.amount, 0);
  const tax = subtotal * 0.05;
  const discount = 50;
  const grandTotal = subtotal + tax - discount;

  const filteredExpenses = tripData.expenses.filter(expense =>
    expense.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
    expense.category.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (authLoading) {
    return (
      <div className="min-h-screen bg-[#F7F9FC] flex items-center justify-center">
        <div className="text-gray-600">Loading...</div>
      </div>
    );
  }

  if (!user) {
    return null;
  }

  return (
    <div className="min-h-screen bg-[#F7F9FC]">
      <div className="max-w-7xl mx-auto px-6 py-6">
        <div className="mb-4">
          <button className="text-[#2E4057] hover:text-[#FF6B35] font-medium flex items-center gap-2">
            ← back to My Trips
          </button>
        </div>

        <div className="flex gap-3 mb-6">
          <input
            type="text"
            placeholder="Search invoices......"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#FF6B35] bg-white text-black"
          />
          <button className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 text-gray-700 font-medium">
            Filter
          </button>
          <button className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 text-gray-700 font-medium">
            Sort
          </button>
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 p-6 mb-6">
          <div className="flex flex-wrap gap-6">
            <div className="flex-1 min-w-[200px]">
              <div className="w-24 h-24 bg-gradient-to-br from-[#FF6B35]/20 to-[#1D976C]/20 rounded-xl flex items-center justify-center mb-3">
                <span className="text-4xl">✈️</span>
              </div>
              <h2 className="text-xl font-bold text-[#2E4057]">{tripData.title}</h2>
              <p className="text-gray-500 mt-1">{tripData.duration}</p>
              <p className="text-sm text-gray-400">{tripData.cities}</p>
            </div>

            <div className="flex-1 min-w-[200px]">
              <h3 className="text-sm font-medium text-gray-500 mb-2">Invoice Details</h3>
              <p className="text-gray-800"><span className="font-medium">Invoice Id:</span> {tripData.invoiceId}</p>
              <p className="text-gray-800"><span className="font-medium">Generated date:</span> {tripData.generatedDate}</p>
              <div className="mt-3">
                <p className="text-sm font-medium text-gray-500 mb-1">Travelers:</p>
                <div className="flex flex-wrap gap-1">
                  {tripData.travelers.map((traveler, i) => (
                    <span key={i} className="px-2 py-1 bg-[#F7F9FC] text-gray-600 text-sm rounded">{traveler}</span>
                  ))}
                </div>
              </div>
            </div>

            <div className="min-w-[200px]">
              <h3 className="text-sm font-medium text-gray-500 mb-2">Payment Status</h3>
              <span className={`px-3 py-1 rounded-full text-sm font-medium ${paymentStatus === 'pending' ? 'bg-yellow-100 text-yellow-700' : 'bg-green-100 text-green-700'}`}>
                Payment status - {paymentStatus}
              </span>
            </div>

            <div className="min-w-[200px] bg-[#F7F9FC] rounded-xl p-4">
              <h3 className="text-sm font-medium text-gray-500 mb-3">Budget Insights</h3>
              <div className="w-24 h-24 mx-auto mb-3">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie data={budgetData} cx="50%" cy="50%" innerRadius={25} outerRadius={40} dataKey="value">
                      {budgetData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.name === 'Spent' ? '#FF6B35' : '#2E4057'} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="text-center text-sm">
                <p className="text-gray-600">Total Budget: <span className="font-bold text-[#2E4057]">${tripData.totalBudget.toLocaleString()}</span></p>
                <p className="text-gray-600">Total Spent: <span className="font-bold text-[#FF6B35]">${tripData.totalSpent.toLocaleString()}</span></p>
                <p className={`font-bold ${budgetRemaining >= 0 ? 'text-[#1D976C]' : 'text-red-500'}`}>
                  Remaining: ${budgetRemaining.toLocaleString()}
                </p>
              </div>
              <button className="w-full mt-3 py-2 bg-[#2E4057] text-white text-sm rounded-lg hover:bg-[#1a2a3d]">
                View Full Budget
              </button>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-[#F7F9FC]">
                <tr>
                  <th className="px-4 py-3 text-left text-sm font-medium text-gray-600">#</th>
                  <th className="px-4 py-3 text-left text-sm font-medium text-gray-600">Category</th>
                  <th className="px-4 py-3 text-left text-sm font-medium text-gray-600">Description</th>
                  <th className="px-4 py-3 text-left text-sm font-medium text-gray-600">Qty/details</th>
                  <th className="px-4 py-3 text-right text-sm font-medium text-gray-600">Unit Cost</th>
                  <th className="px-4 py-3 text-right text-sm font-medium text-gray-600">Amount</th>
                </tr>
              </thead>
              <tbody>
                {filteredExpenses.map((expense, index) => (
                  <tr key={expense.id} className="border-t border-gray-100">
                    <td className="px-4 py-3 text-gray-600">{index + 1}</td>
                    <td className="px-4 py-3">
                      <span className="px-2 py-1 bg-[#FF6B35]/10 text-[#FF6B35] text-xs rounded">{expense.category}</span>
                    </td>
                    <td className="px-4 py-3 text-gray-800">{expense.description}</td>
                    <td className="px-4 py-3 text-gray-600">{expense.qty}</td>
                    <td className="px-4 py-3 text-right text-gray-600">${expense.unitCost.toLocaleString()}</td>
                    <td className="px-4 py-3 text-right font-medium text-gray-800">${expense.amount.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="border-t border-gray-200 p-6 flex justify-end">
            <div className="w-64 space-y-2">
              <div className="flex justify-between text-gray-600">
                <span>Subtotal:</span>
                <span>${subtotal.toLocaleString()}</span>
              </div>
              <div className="flex justify-between text-gray-600">
                <span>Tax (5%):</span>
                <span>${tax.toLocaleString()}</span>
              </div>
              <div className="flex justify-between text-gray-600">
                <span>Discount:</span>
                <span>-${discount}</span>
              </div>
              <div className="flex justify-between text-xl font-bold text-[#2E4057] pt-2 border-t border-gray-200">
                <span>Grand Total:</span>
                <span>${grandTotal.toLocaleString()}</span>
              </div>
            </div>
          </div>
        </div>

        <div className="flex gap-4 mt-6 justify-end">
          <button 
            onClick={downloadInvoice}
            className="px-6 py-3 border border-gray-300 rounded-lg hover:bg-[#2E4057] hover:text-white text-gray-700 font-medium flex items-center gap-2 transition-all duration-200 hover:scale-105 active:scale-95"
          >
            Download Invoice
          </button>
          <button 
            onClick={exportPDF}
            className="px-6 py-3 border border-gray-300 rounded-lg hover:bg-[#2E4057] hover:text-white text-gray-700 font-medium flex items-center gap-2 transition-all duration-200 hover:scale-105 active:scale-95"
          >
            Export as PDF
          </button>
          <button 
            onClick={markAsPaid}
            disabled={paymentStatus === 'paid'}
            className="px-6 py-3 bg-[#1D976C] text-white rounded-lg hover:bg-[#15855a] font-medium disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 hover:scale-105 active:scale-95"
          >
            {paymentStatus === 'paid' ? 'Already Paid' : 'Mark as paid'}
          </button>
        </div>

        {showMessage && (
          <div className="fixed bottom-6 right-6 bg-[#2E4057] text-white px-6 py-3 rounded-lg shadow-lg">
            {showMessage}
          </div>
        )}
      </div>
    </div>
  );
}